name: gocart-v2
services:
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    platform: linux/amd64
    image: gocart-v2-product-service:latest
    ports:
      - "8080:8080"
    container_name: product-service

  cart-service:
    build:
      context: .
      dockerfile: services/cart-service/Dockerfile
    platform: linux/amd64
    image: gocart-v2-cart-service:latest
    ports:
      - "8081:8081"
    container_name: cart-service

  # warehouse-service:
  #   build:
  #     context: .
  #     dockerfile: services/warehouse-service/Dockerfile
  #   platform: linux/amd64
  #   image: gocart-v2-warehouse-service:latest
  #   ports:
  #     - "8082:8082"
  #   container_name: warehouse-service

  # payment-service:
  #   build:
  #     context: .
  #     dockerfile: services/payment-service/Dockerfile
  #   platform: linux/amd64
  #   image: gocart-v2-payment-service:latest
  #   ports:
  #     - "8083:8083"
  #   container_name: payment-service
